/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'koray2' at '4/8/16 5:56 PM' with Gradle 2.6
 *
 * @author koray2, @date 4/8/16 5:56 PM
 */
public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Bil681Project classUnderTest = new Bil681Project();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.main());
//    }
}
